spring:
  application:
    name: chekirout
  profiles:
    active:
      - local
    group:
      local:
        - db-local
      dev:
        - db-dev
#      prod:
#        - db-prod
    include:
      - db
  cloud:
    config:
      server:
        bootstrap: true
firebase:
  service-account-key: ${FIREBASE_SERVICE_ACCOUNT_KEY}